### ISSUE TITLE
fresh install and trying example 3 omindashboard complaining ...

### ISSUE THREAD

**Issue by FasilGibdaw** [JouleCai/geospacelab#9]
`  File "/Users/$USER/opt/anaconda3/lib/python3.9/site-packages/geospacelab/express/omni_dashboard.py", line 29, in __init__
    self.ds_omni.add_NCF()
AttributeError: 'NoneType' object has no attribute 'add_NCF'`

**Comment by JouleCai** [comment]
Thank you for pointing out the issue. That is because python<3.10 does not support the callable statistic method used for building the OMNI Dataset. 

Solution:
1. Upgrade GeospaceLAB to version 0.5.10 or later [recommended].
or
2. Use a newer version of python (later than 3.10).

In addition, the examples in README.md is revalidated. Please use the new codes.

Warning: Currently, the AE indices cannot be downloaded from the data provider: https://wdc.kugi.kyoto-u.ac.jp/aeasy/index.html. The online server has some issues. The example figure may show some blank panels due to the missing data.

**Comment by FasilGibdaw** [comment]
Thank you, will do!

**Comment by JouleCai** [comment]
The AE indices can be downloaded and presented now. The online server works as usual.
